import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { SkeletonTheme } from "react-loading-skeleton";
import Providers from "@/components/app/providers";
import ThemeSelector from "@/components/app/theme-selector";
import AnimationWrapper from "@/components/app/animation-wrapper";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${outfit.className} antialiased`}>
        <SkeletonTheme
          baseColor="var(--bg-600)"
          customHighlightBackground="var(--base-color)"
          duration={2}
        >
          <Providers>
            <AnimationWrapper>
              <ThemeSelector />
              {children}
            </AnimationWrapper>
          </Providers>
        </SkeletonTheme>
      </body>
    </html>
  );
}
