import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { SkeletonTheme } from "react-loading-skeleton";
import Providers from "@/components/app/providers";
import AnimationWrapper from "@/components/app/animation-wrapper";
import Navbar from "@/components/app/navbar";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app/sidebar";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${outfit.className} antialiased`}>
        <SkeletonTheme
          baseColor="var(--bg-600)"
          customHighlightBackground="var(--base-color)"
          duration={2}
        >
          <Providers>
            <AnimationWrapper>
              <SidebarProvider>
                <AppSidebar />
                <Navbar />
                {children}
              </SidebarProvider>
            </AnimationWrapper>
          </Providers>
        </SkeletonTheme>
      </body>
    </html>
  );
}
